Revert "Register stone"
NeoCloud/NeoNetwork pull request #276
Opened 2024-06-23 12:09 UTC by marek22k

Reverts NeoCloud/NeoNetwork#275

2024-06-23 15:03 UTC, isjerryxiao requested changes
Merge temporarily blocked

2024-06-25 17:01 UTC, marek22k commented
@isjerryxiao Can you take a look?

2024-06-26 03:56 UTC, isjerryxiao commented
```
commit 88f72f3c696791feafc9a8c37f81f6ca9d202cdf (HEAD, test/revert-275-stone)
Good "git" signature for stone@unix.dog with ECDSA key SHA256:RdeWJLQUYoUFRxSbLqNg2k+JMohpPzQQ9fIefsPTc7I
Author: Marek Küthe <m.k@mk16.de>
Date:   Tue Jun 18 13:56:30 2024 +0000

    Register stone
    
    This is an entry that I create as part of my registration proxy service.
    Stone added SSH public key.
    
    Signed-off-by: Marek Küthe <m.k@mk16.de>
    Signed-off-by: Stone Fox <stone@unix.dog>

```

2024-06-26 03:57 UTC, isjerryxiao approved these changes

2024-06-26 03:57 UTC, merged